# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
 - hadley/devtools#1263
 - rte-antares-rpackage/antaresHDF5

r_packages:
  - covr

include:
  - r: release
  - r: oldrel
  - r: devel

after_success:
  - Rscript -e 'library(covr); codecov()'
